"""adiciona modelos legados Comando e ComandoTemplate

Revision ID: c5d5de836eaa
Revises: dc38df133f34
Create Date: 2026-09-08 11:55:35.253931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d5de836eaa'
down_revision: Union[str, None] = 'dc38df133f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comando_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('comando', sa.Text(), nullable=False),
    sa.Column('criado_por', sa.String(), nullable=True),
    sa.Column('criado_em', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comandos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_serie', sa.String(), nullable=False),
    sa.Column('comando', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('codigo_saida', sa.Integer(), nullable=True),
    sa.Column('criado_por', sa.String(), nullable=True),
    sa.Column('criado_em', sa.String(), nullable=False),
    sa.Column('executado_em', sa.String(), nullable=True),
    sa.Column('agendado_para', sa.String(), nullable=True),
    sa.Column('modo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comandos')
    op.drop_table('comando_templates')
    # ### end Alembic commands ###
