"""adiciona modelos legados Ativo e Monitoramento

Revision ID: dc38df133f34
Revises: 4aae497a4dd0
Create Date: 2026-09-08 11:21:22.624593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc38df133f34'
down_revision: Union[str, None] = '4aae497a4dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ativos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('numero_serie', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('responsavel', sa.String(), nullable=True),
    sa.Column('localizacao', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('patrimonio', sa.String(), nullable=True),
    sa.Column('usuario', sa.String(), nullable=True),
    sa.Column('modelo_monitor', sa.String(), nullable=True),
    sa.Column('patrimonio_monitor', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitoramento',
    sa.Column('numero_serie', sa.String(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('sistema_operacional', sa.String(), nullable=True),
    sa.Column('armazenamento_total_gb', sa.Float(), nullable=True),
    sa.Column('armazenamento_usado_gb', sa.Float(), nullable=True),
    sa.Column('armazenamento_livre_gb', sa.Float(), nullable=True),
    sa.Column('uso_cpu_percent', sa.Float(), nullable=True),
    sa.Column('uso_memoria_percent', sa.Float(), nullable=True),
    sa.Column('uso_disco_percent', sa.Float(), nullable=True),
    sa.Column('rede_enviado_mb', sa.Float(), nullable=True),
    sa.Column('rede_recebido_mb', sa.Float(), nullable=True),
    sa.Column('ultima_atualizacao', sa.String(), nullable=True),
    sa.Column('patrimonio', sa.String(), nullable=True),
    sa.Column('usuario', sa.String(), nullable=True),
    sa.Column('modelo_monitor', sa.String(), nullable=True),
    sa.Column('patrimonio_monitor', sa.String(), nullable=True),
    sa.Column('fila_pendente_local', sa.Integer(), nullable=True),
    sa.Column('memoria_total_gb', sa.Float(), nullable=True),
    sa.Column('memoria_usada_gb', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('numero_serie')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitoramento')
    op.drop_table('ativos')
    # ### end Alembic commands ###
